kind: Secret
apiVersion: v1
metadata:
  namespace: vplugin-demo
  name: example-secret-vault
  annotations:
    avp.kubernetes.io/path: "secret/data/vplugin/supersecret"
type: Opaque
stringData:
  username: <username>
  password: <password>
