{{- if .Values.secret.create -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
{{- end }}
